### ISSUE TITLE
Улучшить структуру кода react-suggest/src/components/SuggestInput/SuggestInput.js       

### ISSUE THREAD

**Issue by andrey-ilyin** [kazak13-1990/react-suggest#1]
1. Надо избавиться от дублирования кода в методе onKeyPress 
2. Надо переработать метод render(). Сейчас метод сложно воспринимается.

**Comment by kazak13-1990** [comment]
1. Исправил
2. Вынес список в отдельный компонент

**Comment by andrey-ilyin** [comment]
Принято.
