### ISSUE TITLE
Улучшить структуру кода js-suggest/src/components/SuggestInput/SuggestInput.js       

### ISSUE THREAD

**Issue by andrey-ilyin** [kazak13-1990/react-suggest#2]
1. Метод renderSuggests() нуждается в рефакторинге
2. Дублирование кода onKeyPress(event)

**Comment by kazak13-1990** [comment]
1. Вынес в отдельные функции создание списка и создание элемента
2. Исправил

**Comment by andrey-ilyin** [comment]
Принято.
